-- Tapvora MVP database
-- Run this once in the Supabase SQL editor, then create an Auth user and add
-- their UUID to app_admins at the bottom of this file.

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.cards (
  id uuid primary key default gen_random_uuid(),
  card_number bigint generated by default as identity unique not null,
  code text unique not null check (code ~ '^[A-Z2-9]{5,10}$'),
  business_name text,
  destination_url text check (destination_url is null or destination_url ~ '^https://'),
  status text not null default 'unused' check (status in ('unused', 'active', 'inactive')),
  notes text,
  redirect_count bigint not null default 0 check (redirect_count >= 0),
  last_redirected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint active_card_is_complete check (
    status <> 'active' or (business_name is not null and destination_url is not null)
  )
);

create index if not exists cards_code_idx on public.cards(code);
create index if not exists cards_status_idx on public.cards(status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cards_set_updated_at on public.cards;
create trigger cards_set_updated_at
before update on public.cards
for each row execute function public.set_updated_at();

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.app_admins where user_id = auth.uid()
  );
$$;

alter table public.app_admins enable row level security;
alter table public.cards enable row level security;

drop policy if exists "Admins can read own membership" on public.app_admins;
create policy "Admins can read own membership"
on public.app_admins for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Admins can read cards" on public.cards;
create policy "Admins can read cards"
on public.cards for select
to authenticated
using (public.is_app_admin());

drop policy if exists "Admins can insert cards" on public.cards;
create policy "Admins can insert cards"
on public.cards for insert
to authenticated
with check (public.is_app_admin());

drop policy if exists "Admins can update cards" on public.cards;
create policy "Admins can update cards"
on public.cards for update
to authenticated
using (public.is_app_admin())
with check (public.is_app_admin());

-- Public, minimal resolver. It reveals no card inventory and records an open
-- only when the card is active and has a destination.
create or replace function public.resolve_card_redirect(requested_code text)
returns table (destination_url text, card_status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched public.cards%rowtype;
begin
  select * into matched
  from public.cards
  where code = upper(requested_code)
  limit 1;

  if not found then
    return;
  end if;

  if matched.status = 'active' and matched.destination_url is not null then
    update public.cards
    set redirect_count = redirect_count + 1,
        last_redirected_at = now()
    where id = matched.id;
  end if;

  return query select matched.destination_url, matched.status;
end;
$$;

revoke all on function public.resolve_card_redirect(text) from public;
grant execute on function public.resolve_card_redirect(text) to anon, authenticated;

-- After creating your private admin in Authentication → Users, run:
-- insert into public.app_admins (user_id) values ('YOUR-AUTH-USER-UUID');
