-- Stores anonymous open timestamps for real dashboard analytics.
-- No IP address, device identifier, location, or user agent is collected.

create table if not exists public.redirect_events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.cards(id) on delete cascade,
  opened_at timestamptz not null default now()
);

create index if not exists redirect_events_card_id_idx
on public.redirect_events(card_id);

create index if not exists redirect_events_opened_at_idx
on public.redirect_events(opened_at desc);

alter table public.redirect_events enable row level security;

drop policy if exists "Admins can read redirect events" on public.redirect_events;
create policy "Admins can read redirect events"
on public.redirect_events for select
to authenticated
using (public.is_app_admin());

create or replace function public.resolve_card_redirect(requested_code text)
returns table (destination_url text, card_status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched public.cards%rowtype;
begin
  select * into matched
  from public.cards
  where code = upper(requested_code)
  limit 1;

  if not found then
    return;
  end if;

  if matched.status = 'active' and matched.destination_url is not null then
    update public.cards
    set redirect_count = redirect_count + 1,
        last_redirected_at = now()
    where id = matched.id;

    insert into public.redirect_events (card_id) values (matched.id);
  end if;

  return query select matched.destination_url, matched.status;
end;
$$;

revoke all on function public.resolve_card_redirect(text) from public;
grant execute on function public.resolve_card_redirect(text) to anon, authenticated;
